In [1]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('weatherAUS.csv')
# X = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, 3].values

In [3]:
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

In [4]:
dataset.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [5]:
dataset.count().sort_values()

Sunshine          74377
Evaporation       81350
Cloud3pm          85099
Cloud9am          88536
Pressure9am      128179
Pressure3pm      128212
WindDir9am       132180
WindGustDir      132863
WindGustSpeed    132923
WindDir3pm       138415
Humidity3pm      138583
Temp3pm          139467
WindSpeed3pm     139563
Humidity9am      140419
RainToday        140787
Rainfall         140787
WindSpeed9am     140845
Temp9am          141289
MinTemp          141556
MaxTemp          141871
Date             142193
Location         142193
RISK_MM          142193
RainTomorrow     142193
dtype: int64

In [6]:
dataset.shape

(142193, 24)

In [7]:
dataset.drop(labels = ['Date','Location','Evaporation','Sunshine','Cloud3pm','Cloud9am','RISK_MM'],axis = 1,inplace = True)

In [8]:
dataset.head()

MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0     13.4     22.9       0.6           W           44.0          W   
1      7.4     25.1       0.0         WNW           44.0        NNW   
2     12.9     25.7       0.0         WSW           46.0          W   
3      9.2     28.0       0.0          NE           24.0         SE   
4     17.5     32.3       1.0           W           41.0        ENE   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   

   Pressure9am  Pressure3pm  Temp9am  Temp3pm RainToday RainTomorrow  
0       1007.7       1007.1     16.9     21.8        No           No  
1       1010.6       1007.8     17.2     24.3        No           No  
2       1007.6       1008.7     21.0     23.2        No           No  
3       1017.6       1012.8     18.1     26.5        No           No  
4       1010.8       1006.0     17.8     29.7        No           No

In [9]:
dataset.describe()

MinTemp        MaxTemp       Rainfall  WindGustSpeed  \
count  141556.000000  141871.000000  140787.000000  132923.000000   
mean       12.186400      23.226784       2.349974      39.984292   
std         6.403283       7.117618       8.465173      13.588801   
min        -8.500000      -4.800000       0.000000       6.000000   
25%         7.600000      17.900000       0.000000      31.000000   
50%        12.000000      22.600000       0.000000      39.000000   
75%        16.800000      28.200000       0.800000      48.000000   
max        33.900000      48.100000     371.000000     135.000000   

        WindSpeed9am   WindSpeed3pm    Humidity9am    Humidity3pm  \
count  140845.000000  139563.000000  140419.000000  138583.000000   
mean       14.001988      18.637576      68.843810      51.482606   
std         8.893337       8.803345      19.051293      20.797772   
min         0.000000       0.000000       0.000000       0.000000   
25%         7.000000      13.000000      57.000000      37.000000   
50%        13.000000      19.000000      70.000000      52.000000   
75%        19.000000      24.000000      83.000000      66.000000   
max       130.000000      87.000000     100.000000     100.000000   

         Pressure9am    Pressure3pm        Temp9am        Temp3pm  
count  128179.000000  128212.000000  141289.000000  139467.000000  
mean     1017.653758    1015.258204      16.987509      21.687235  
std         7.105476       7.036677       6.492838       6.937594  
min       980.500000     977.100000      -7.200000      -5.400000  
25%      1012.900000    1010.400000      12.300000      16.600000  
50%      1017.600000    1015.200000      16.700000      21.100000  
75%      1022.400000    1020.000000      21.600000      26.400000  
max      1041.000000    1039.600000      40.200000      46.700000

In [10]:
dataset.dropna(inplace=True)

In [11]:
dataset.shape

(112925, 17)

In [12]:
dataset.head()

MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0     13.4     22.9       0.6           W           44.0          W   
1      7.4     25.1       0.0         WNW           44.0        NNW   
2     12.9     25.7       0.0         WSW           46.0          W   
3      9.2     28.0       0.0          NE           24.0         SE   
4     17.5     32.3       1.0           W           41.0        ENE   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   

   Pressure9am  Pressure3pm  Temp9am  Temp3pm RainToday RainTomorrow  
0       1007.7       1007.1     16.9     21.8        No           No  
1       1010.6       1007.8     17.2     24.3        No           No  
2       1007.6       1008.7     21.0     23.2        No           No  
3       1017.6       1012.8     18.1     26.5        No           No  
4       1010.8       1006.0     17.8     29.7        No           No

In [13]:
#its time to remove the outliers in our data - we are using Z-score to detect and remove the outliers.
from scipy import stats
z = np.abs(stats.zscore(dataset._get_numeric_data()))
print(z)
dataset= dataset[(z < 3).all(axis=1)]
print(dataset.shape)

[[0.11756741 0.10822071 0.20666127 ... 1.14245477 0.08843526 0.04787026]
 [0.84180219 0.20684494 0.27640495 ... 1.04184813 0.04122846 0.31776848]
 [0.03761995 0.29277194 0.27640495 ... 0.91249673 0.55672435 0.15688743]
 ...
 [1.44940294 0.23548728 0.27640495 ... 0.58223051 1.03257127 0.34701958]
 [1.16159206 0.46462594 0.27640495 ... 0.25166583 0.78080166 0.58102838]
 [0.77784422 0.4789471  0.27640495 ... 0.2085487  0.37167606 0.56640283]]
(107868, 17)


In [14]:
dataset['RainTomorrow'].replace({'No':0, 'Yes':1}, inplace=True)

In [15]:
dataset['RainToday'].replace({'No':0, 'Yes':1}, inplace=True)

In [16]:
dataset.tail()

MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
142188      3.5     21.8       0.0           E           31.0        ESE   
142189      2.8     23.4       0.0           E           31.0         SE   
142190      3.6     25.3       0.0         NNW           22.0         SE   
142191      5.4     26.9       0.0           N           37.0         SE   
142192      7.8     27.0       0.0          SE           28.0        SSE   

       WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
142188          E          15.0          13.0         59.0         27.0   
142189        ENE          13.0          11.0         51.0         24.0   
142190          N          13.0           9.0         56.0         21.0   
142191        WNW           9.0           9.0         53.0         24.0   
142192          N          13.0           7.0         51.0         24.0   

        Pressure9am  Pressure3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  
142188       1024.7       1021.2      9.4     20.9          0             0  
142189       1024.6       1020.3     10.1     22.4          0             0  
142190       1023.5       1019.1     10.9     24.5          0             0  
142191       1021.0       1016.8     12.5     26.1          0             0  
142192       1019.4       1016.5     15.1     26.0          0             0

In [17]:
dataset.head()

MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0     13.4     22.9       0.6           W           44.0          W   
1      7.4     25.1       0.0         WNW           44.0        NNW   
2     12.9     25.7       0.0         WSW           46.0          W   
3      9.2     28.0       0.0          NE           24.0         SE   
4     17.5     32.3       1.0           W           41.0        ENE   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   

   Pressure9am  Pressure3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  
0       1007.7       1007.1     16.9     21.8          0             0  
1       1010.6       1007.8     17.2     24.3          0             0  
2       1007.6       1008.7     21.0     23.2          0             0  
3       1017.6       1012.8     18.1     26.5          0             0  
4       1010.8       1006.0     17.8     29.7          0             0

In [18]:
dataset.dropna(inplace = True)

In [19]:
dataset.shape

(107868, 17)

In [20]:
categorical = ['WindGustDir','WindDir9am','WindDir3pm']

In [21]:
dataset = pd.get_dummies(dataset,columns = categorical,drop_first=True)

In [22]:
dataset.head()

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0     13.4     22.9       0.6           44.0          20.0          24.0   
1      7.4     25.1       0.0           44.0           4.0          22.0   
2     12.9     25.7       0.0           46.0          19.0          26.0   
3      9.2     28.0       0.0           24.0          11.0           9.0   
4     17.5     32.3       1.0           41.0           7.0          20.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir3pm_NNW  \
0         71.0         22.0       1007.7       1007.1  ...               0   
1         44.0         25.0       1010.6       1007.8  ...               0   
2         38.0         30.0       1007.6       1008.7  ...               0   
3         45.0         16.0       1017.6       1012.8  ...               0   
4         82.0         33.0       1010.8       1006.0  ...               0   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0              0             0              0               0               0   
1              0             0              0               0               0   
2              0             0              0               0               0   
3              0             0              0               0               0   
4              1             0              0               0               0   

   WindDir3pm_SW  WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0              0             0               1               0  
1              0             0               0               1  
2              0             0               0               1  
3              0             0               0               0  
4              0             0               0               0  

[5 rows x 59 columns]

In [23]:
dataset.shape

(107868, 59)

In [24]:
dataset.iloc[10:12,:-1]

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
10     13.4     30.4       0.0           30.0          17.0           6.0   
11     15.9     21.7       2.2           31.0          15.0          13.0   

    Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir3pm_NNE  \
10         48.0         22.0       1011.8       1008.7  ...               0   
11         89.0         91.0       1010.5       1004.2  ...               0   

    WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
10               0              0             0              0   
11               0              0             0              0   

    WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW  WindDir3pm_W  \
10               0               0              0             0   
11               0               0              0             0   

    WindDir3pm_WNW  
10               0  
11               0  

[2 rows x 58 columns]

In [25]:
dataset.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow',
       'WindGustDir_ENE', 'WindGustDir_ESE', 'WindGustDir_N', 'WindGustDir_NE',
       'WindGustDir_NNE', 'WindGustDir_NNW', 'WindGustDir_NW', 'WindGustDir_S',
       'WindGustDir_SE', 'WindGustDir_SSE', 'WindGustDir_SSW',
       'WindGustDir_SW', 'WindGustDir_W', 'WindGustDir_WNW', 'WindGustDir_WSW',
       'WindDir9am_ENE', 'WindDir9am_ESE', 'WindDir9am_N', 'WindDir9am_NE',
       'WindDir9am_NNE', 'WindDir9am_NNW', 'WindDir9am_NW', 'WindDir9am_S',
       'WindDir9am_SE', 'WindDir9am_SSE', 'WindDir9am_SSW', 'WindDir9am_SW',
       'WindDir9am_W', 'WindDir9am_WNW', 'WindDir9am_WSW', 'WindDir3pm_ENE',
       'WindDir3pm_ESE', 'WindDir3pm_N', 'WindDir3pm_NE', 'WindDir3pm_NNE',
       'WindDir3pm_NNW', 'WindDir3pm_NW', 'WindDir3pm_S', 'WindDir3pm_SE',
       'WindDir3pm_SSE', 

In [26]:
X = dataset.drop(labels = ['RainTomorrow'],axis = 1)

In [27]:
X.shape

(107868, 58)

In [28]:
y = dataset['RainTomorrow']

In [29]:
y.shape

(107868,)

In [30]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [31]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
#sc_y = StandardScaler()
#y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [32]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [33]:
# print(classification_report(y_test,y_pred))

In [34]:
# print('Training accuracy ---->',accuracy_score(y_train,y_train_pred))
# print('Testing accuracy  ---->',accuracy_score(y_test,y_pred))

In [35]:
#Logistic Regression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import time

t0=time.time()
clf_logreg = LogisticRegression(random_state=0)
clf_logreg.fit(X_train,y_train)
y_pred = clf_logreg.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)
print(classification_report(y_test,y_pred))

Accuracy : 0.8539445628997868
Time taken : 1.188589096069336
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     17129
           1       0.72      0.47      0.57      4445

    accuracy                           0.85     21574
   macro avg       0.80      0.71      0.74     21574
weighted avg       0.84      0.85      0.84     21574



In [36]:
#Random Forest Classifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_rf = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0)
clf_rf.fit(X_train,y_train)
y_pred = clf_rf.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)
print(classification_report(y_test,y_pred))

Accuracy : 0.8228204842956206
Time taken : 4.789261102676392
              precision    recall  f1-score   support

           0       0.82      0.99      0.90     21323
           1       0.84      0.19      0.31      5644

    accuracy                           0.82     26967
   macro avg       0.83      0.59      0.60     26967
weighted avg       0.83      0.82      0.78     26967



In [37]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train,y_train)
y_pred = clf_dt.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)
print(classification_report(y_test,y_pred))

Accuracy : 0.7935995846775689
Time taken : 1.980860948562622
              precision    recall  f1-score   support

           0       0.87      0.87      0.87     21294
           1       0.51      0.52      0.51      5673

    accuracy                           0.79     26967
   macro avg       0.69      0.69      0.69     26967
weighted avg       0.80      0.79      0.79     26967



In [38]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)
print(classification_report(y_test,y_pred))

Accuracy : 0.7158378759224236
Time taken : 0.3228161334991455
              precision    recall  f1-score   support

           0       0.88      0.74      0.81     21415
           1       0.38      0.62      0.47      5552

    accuracy                           0.72     26967
   macro avg       0.63      0.68      0.64     26967
weighted avg       0.78      0.72      0.74     26967



In [39]:
# K-Neighbours Model fitting
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
score= accuracy_score(y_test, y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)
print(classification_report(y_test,y_pred))

Accuracy : 0.8402491934586717
Time taken : 24.607269525527954
              precision    recall  f1-score   support

           0       0.87      0.93      0.90     21415
           1       0.65      0.48      0.55      5552

    accuracy                           0.84     26967
   macro avg       0.76      0.71      0.73     26967
weighted avg       0.83      0.84      0.83     26967

